apiVersion: v1
kind: ConfigMap
metadata:
  name: gnb-cmap
  labels:
    nf-type: gnb
data:
  gnb.yaml: |
    mcc: '{{ .Values.gnb.configuration.mcc }}'      
    mnc: '{{ .Values.gnb.configuration.mnc }}'      

    nci: '{{ .Values.gnb.configuration.nci }}'
    idLength: {{ .Values.gnb.configuration.idLength }}
    tac: {{ .Values.gnb.configuration.tac }}

    linkIp: '{{ .Values.gnb.configuration.linkIp }}'
    ngapIp: '{{ .Values.gnb.configuration.ngapIp }}'
    gtpIp: '{{ .Values.gnb.configuration.gtpIp }}'

    # List of AMF address information
    amfConfigs:
    {{- range .Values.gnb.configuration.amfConfigs }}
      - address: '{{ .address }}'
        port: {{ .port }}
    {{- end }}

    # List of supported S-NSSAIs by this gNB
    slices:
    {{- range .Values.gnb.configuration.slices }}
      - sst: {{ .sst }}
        sd: '{{ .sd }}'
    {{- end }}

    ignoreStreamIds: {{ .Values.gnb.configuration.ignoreStreamIds }}
