apiVersion: v1
kind: ConfigMap
metadata:
  name: tun-interface-cmap
  labels:
    nf-type: upf
data:
  tun-interface.sh: |
    #!/bin/bash
    
    set -e

    echo "Executing  tun-interface.sh"

    {{- range .Values.upf.configuration.subnet_list }}
    echo "Creating net device {{ .dev }}"
    if grep "{{ .dev }}" /proc/net/dev > /dev/null; then
        echo "Warning: Net device {{ .dev }} already exists! May you need to set createDev: false"
    else
        ip tuntap add name {{ .dev }} mode tun
        ip link set {{ .dev }} up
    fi

    echo "Setting IP {{ .addr }} to device {{ .dev }}"
    if ip addr show {{ .dev }} | grep -q "{{ .addr }}"; then
        echo "IP {{ .addr }} is already assigned to {{ .dev }}"
    else
        ip addr add {{ .addr }} dev {{ .dev }}
    fi

    sysctl -w net.ipv4.ip_forward=1
    echo "Enable NAT for {{ .addr }} and device {{ .dev }}"

    apt-get install -y iptables
    iptables -t nat -A POSTROUTING -s {{ .addr }} ! -o {{ .dev }} -j MASQUERADE

    
    {{- end }}

    $@